services:
    django:
        build: ./django
        command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
        ports:
            - 8000:8000
        volumes:
            - ./src:/code