services:
    django1:
        build: ./django
        command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
        expose:
            - 8000
        volumes:
            - ./src:/code
        depends_on:
            - db
    django2:
        build: ./django
        command: uvicorn config.asgi:application --host 0.0.0.0 --port 8001
        expose:
            - 8001
        volumes:
            - ./src:/code
        depends_on:
            - db
    db:
        image: postgres:15.4
        volumes:
            - db-store:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=test
            - POSTGRES_DB=testdb
    nginx:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./src/collected_static:/static
        depends_on:
            - django1
            - django2

volumes:
  db-store: